```{r}
GAM <- read.csv('./Modi5Dementia.csv')[,-1]
```

```{r}
library(caret)
library(randomForest)
library(dplyr)
library(stringr)
library(party)
# 인공신경망
library(nnet)
# SVM
library(e1071)
```

```{r}
GAM
GAM[,c(1,2,4,5,6)]
```

### 사용할 컬럼 Age, Gender, MMSE, CDR, EDUC 제외하고 없애기

```{r}
GAM <- GAM[,c(1,2,4,5,6)]
```

CDR factor로 바꾸기

```{r}
GAM$CDR <- as.factor(GAM$CDR)
```

### CDR 별로 나누기

```{r}
CDR1 <- subset(GAM, CDR == '1')
nrow(CDR1) # = 38
CDR5 <- subset(GAM, CDR == '0.5')
nrow(CDR5) # = 110
CDR0 <- subset(GAM, CDR == '0')
nrow(CDR0) # = 205

```

==================================================================

### sample Data

```{r}
sample1 <- sample(1:38,38)
sample5 <- sample(1:110,38)
sample0 <- sample(1:205,38)

test.CDR1 <- CDR1[sample1,]
test.CDR5 <- CDR5[sample5,]
test.CDR0 <- CDR0[sample0,]

#data.CDR1 <- CDR1[-sample,]  # 38 다 사용해서 CDR1은 그대로 사용 
#nrow(data.CDR1)
data.CDR5 <- CDR5[-sample5,] 
#nrow(data.CDR5)
data.CDR0 <- CDR0[-sample0,] 
#nrow(data.CDR0)
#data.CDR5


testCDR <- rbind(test.CDR1,test.CDR0,test.CDR5)
#dataCDR <- rbind(data.CDR1,data.CDR5,data.CDR0)  # 38 다 사용해서 CDR1은 그대로 사용 
dataCDR <- rbind(test.CDR1,data.CDR5,data.CDR0)
#dataCDR
#nrow(dataCDR) # 277
#nrow(testCDR) # 114

# rbind 한거 순서 한번 섞기
sample <- sample(1:114,114)
testCDR <- testCDR[sample,]


sample <- sample(1:277,277)
dataCDR <- dataCDR[sample,]
nrow(dataCDR)
```

### AI

# 인공신경망

```{r}
x <- subset(testCDR , select = -CDR)
y <- testCDR$CDR
```

```{r}
model.nnet <- nnet(CDR ~ ., data = dataCDR, size = 3)
pred <- predict(model.nnet, x, type = "class")
pred
```

```{r}
pred == y
mean(pred == y)*100
```

```{r}
table(pred,y)
```

# RandomForest

```{r}
x <- subset(testCDR, select = -CDR)
y <- testCDR$CDR
rf <- randomForest(CDR ~ ., data = dataCDR, ntree = 100) 
rf
```

```{r}
pred <- predict(rf, x)
mean(pred == y)
table(pred,y)
#saveRDS(rf,'./AI/randomForest_iris.rds')

```

# 가장 높은 예측율 가진 모델 RandomForest 저장

```{r}
rf <- randomForest(CDR ~ ., data = GAM, ntree = 100) 

saveRDS(rf,'./AI/randomForest_iris.rds')
```

# SVM

```{r}

x <- subset(testCDR, select = -CDR)
y <- testCDR$CDR
model <- svm(CDR ~., data = dataCDR)
```

```{r}
pred <- predict(model,x)
mean(pred == y)
```

```{r}
table(pred,y)
```

# 의사결정나무

```{r}
x <- subset(testCDR, select = -CDR)
y <- testCDR$CDR
#학습시키기
dementia_tree <- ctree(CDR ~ ., data = dataCDR)
pred <- predict(dementia_tree, x)
```

```{r}
mean(pred == y)
table(pred, y)
```
