# 행정안전부 주민등록 인구 및 세대현황

-   <https://jumin.mois.go.kr/ageStatMonth.do>

```{r}
#str
library(stringr)
# arrange
library(dplyr)
```

```{r}
y1415 <- read.csv('./201412_201512.csv', header = T, fileEncoding = "euc-kr")
y1621 <- read.csv('./201612_202112.csv', header = T, fileEncoding = "euc-kr")
tail(y1621)
```

### 불필요한 로우컬럼 삭제

```{r}
#불 필요한 칼럼,로우 삭제
# row1 전국 삭제
# 이번에는 성별비율은 필요가 없으므로 성별을 없애고 계 나이만 살릴예정


# 14~15년도 총 계만 살리고 남/여 컬럼 삭제 
y1415 <- y1415[-1,-c(2:3,15:40)] # 14년 0~ 100세이상
y1415 <-y1415[,-c(13:14,26:ncol(y1415))]


# y 1620 에 구군 삭제
y1621 <- y1621[c(1,27,44,53,68,74,80,87:88,143,163,179,197,216,239,265,292),]

# 16~21년도 총 계만 살리고 남/여 컬럼 삭제
y1621 <- y1621[,-c(2:3,15:42)] # 16년도
y1621 <- y1621[,-c(24:51)]  # 17년도
y1621 <- y1621[,-c(35:62)]  # 18년도 
y1621 <- y1621[,-c(46:73)]  # 19년도 
y1621 <- y1621[,-c(57:84,96: ncol(y1621))]  # 20~21 년도

y1415
y1621
```

### 행정구역 한글로 바꾸기

```{r}

y1415$행정구역<-unlist(str_extract_all(y1415$행정구역,"[가-횧]{1,}")) # 행정구역 바꾸기
y1621$행정구역<-unlist(str_extract_all(y1415$행정구역,"[가-횧]{1,}")) # 행정구역 바꾸기

length(unlist(str_extract_all(y1415$행정구역,"[가-횧]{1,}"))) # 행정구역 17개 확인
length(unlist(str_extract_all(y1621$행정구역,"[가-횧]{1,}"))) # 행정구역 17개 
```

### column 이름 변경

```{r}

# colnames 컬럼 이름 변경 
colnames(y1415)<- c('행정구역',rep(c('0-9','10-19','20-29','30-39','40-49','50-59','60-69','70-79','80-89','90-99','100-'),2))

colnames(y1621)<- c('행정구역',rep(c('0-9','10-19','20-29','30-39','40-49','50-59','60-69','70-79','80-89','90-99','100-'),6))


#서울특별시, 인천광역시, 경기도를 수도권으로 이름을 바꾸기
#y1415[c(1,4,8),1] <- "수도권"
#y1415[-c(1,4,8),1] <-"비수도권"
```

### 숫자에 , 없애고 numeric으로 변경

```{r}

for(i in 2:ncol(y1415)){
  y1415[,i] <- str_remove_all(y1415[,i],',') 
  y1415[,i] <- as.numeric(y1415[,i])
}

for(i in 2:ncol(y1621)){
  y1621[,i] <- str_remove_all(y1621[,i],',')
  y1621[,i] <- as.numeric(y1621[,i])
}
y1415
y1621
```

### 14년\~ 20년 합치기

```{r}

#row 정렬 

#행정구역명 적혀있는 1칼럼 없애고 합치기 
y1421 <- cbind(y1415[,-1],y1621[,-1])

# row number 없애기 
rownames(y1421) <- c()

# column 이름 재조정
colnames(y1421)<- c(rep(c('0-9','10-19','20-29','30-39','40-49','50-59','60-69','70-79','80-89','90-99','100-'),8))

y1421
```

### DataFrame 세로로 새로 만들기 -1

### 갯수

```{r}
# 갯수 확인하기

# 년도 2014 - 2021 =  8개 
# 행정구역 갯수    = 17개
# 연령대           = 11개

```

### 세로 데이터 rbind로 ytemp 생성

```{r}

# data1421에 삽입할 temp 만들기 
ytemp <- c()

for(i in seq(1,89,11)){
  ytemp <- rbind(ytemp,t(y1421[1:17, i:(i+10)]))
}

ytemp
#rownames 지우기
rownames(ytemp)<- c()
```

### DataFrame 세로로 새로 만들기 -2 생성

```{r}
#년도  나이  서울특별시 부산광역시 인천광역시 광주광역시 대전 광역시 울산 ....


년도 <- rep(2014:2021, each = 11)
나이 <- rep(c('0-9','10-19','20-29','30-39','40-49','50-59','60-69','70-79','80-89','90-99','100-') , 8)

data1421 <- data.frame(년도,나이)

data1421

tail(data1421)
```

### dataFrame 에 ytemp 합치기

```{r}
Fdata1421 <- cbind(data1421 , ytemp)

# column 이름 추가 
colnames(Fdata1421) <- c('년도','나이','서울특별시','부산광역시','대구광역시','인천광역시','광주광역시','대전광역시','울산광역시','세종특별시','경기도','강원도','충청북도','충청남도','전라북도','전라남도','경상북도','경상남도','제주특별시')

tail(y1415)
```

```{r}
# 잘 만들어 졌나 확인 
Fdata1421
```

## 데이터 저장

```{r}
write.csv(Fdata1421,file="행정안전부_주민등록_인구_및_세대현황.csv")
```
