# For

```{r}
for(i in 10){
  print(i)
}
```

```{r}
for(i in c(1,3,5)){
  print(i)
}
```

1\~100까지의 홀수만 출력하기 (세로로 길어져서 10까지만 함 )

```{r}
for(i in seq(1,10,2)){
  print(i)
}

```

```{r}

for(i in 100){
  print(seq(1,i,2))
}
```

```{r}
for(i in seq(1,10,1)){
  print(sqrt(i))
}

```

```{r}
for(i in seq(1,10,1)){
  print(paste(i,"=>",sqrt(i)))
}
```

```{r}
for(i in seq(1,10,1)){
  cat( paste(i,"=>",sqrt(i)),\n)
}
```

##강사님 답안

```{r}
for(i in 1:10){
  cat(paste(i,"=>",sqrt(i),"\n"))
}
```

1부터 100까지의 짝수의 합계 구하기

```{r}
data <- 1:100
sum <- 0
for(i in data){
  if(i%%2==0){
    sum =sum+i
  }
}
print(paste(data[1],"부터",data[(length(data))],"까지의 합은",sum,"입니다"))


```

위에껀 너무 자바고 바꿈 \<\< 밑에껀 실패함 근데 R에서는 for 잘 안쓰니깐 ..

```{r}
# replace 써서 홀수는 0 으로 짝수는 그대로
data <- 1:100
for(i in data){
  if(i%%2!=0){
    replace(i,i,0)
  i=i+i
  }
  
}   # #이거 틀린 답. replace 사용해서 해볼까 했는데 잘 안됬음
print(paste(data[1],"부터",data[(length(data))],"까지의 합은",i,"입니다"))

```

```{r}
data <- 1:100
sum <- 0
for(i in data){
  ifelse(i%%2==0, sum=sum+i,sum=sum+0)
}
print(paste(data[1],"부터",data[(length(data))],"까지의 합은",sum,"입니다"))
```

```{r}
excel2 <- read.csv("./Data/excel.csv")
head(excel2)
```

Q3 column으로 계산해보겠따1

```{r}
data3 <- excel2$q3
sumEven <- sumOdd <-0  # 이렇게 하면 한번에 초기화 가능함 

for(i in data3){
  if(i %% 2 == 0){
    sumEven = sumEven+i
  }else{
    sumOdd = sumOdd+i
  }
}
cat ("홀수의 합은", sumOdd, "이고 짝수의 합은",sumEven,"입니다")
```

### 99단

```{r}
for (i in 1:9){
  cat("2 X ",i," = ",2*i,"\n")
}
```

## Function

,

```{r}
gugu <- function(a){
    for (i in 1:9){
    cat(a," X ",i," = ",a*i,"\n")
  }
}
```

```{r}
gugu(3)
```

```{r}
gugu3 <- function(x,y){
  for(i in 1: y){
    cat(x," X ",i," = ",x*i,"\n")
  }
}

```

```{r}
gugu3(2,12)
```

```{r}
#홀수 없애기 for+for seq 
x <-seq(2,8,2)

gugu4 <- function(){
  for(i in x){
    cat(i," X ",x," = ", i*x,"\n") 
  }
}

gugu5 <- function(){
  for(i in x){
    for(j in x){
      cat(i," X ", j," = ",i*j,"\n")
    }
    cat("------------","\n")
  }
}
gugu5()

gugu4()
```

```{r}
score <- c(85, 95, 89)
name <- c("Yubi","KwanU","Jangbi")

j<-1
for(i in score){
  cat(name[j], " : ",i,"\n")
  j=j+1
}

# Java 스러운 생각 
```

```{r}

cat(paste(name, ":", score,"\n"),sep ="")
```

# While

```{r}

i <- 0
while(i <10){
  i=i+1
  print(i)
}
```

```{r}
i <- 0
while(T){
  i=i+1
  print(i)
  if(i>9){
    break
  }
}
```

# Repeat

R에서 굉장히 특이한 command. ()가 없다

```{r}
i <- 0
repeat{
  i = i+1
  if(i>10){
    break
  }
  print(i)
}

```
