# 몬테카를로 시뮬레이션

데이터가 없을 경우 가상의 데이터로 테스트 ?

### 동전의 앞면 뒷면 시뮬레이션

```{r}
x <- runif(1)
  if( x <= 1/2){
    result = 0 # Front
  }else{
    result = 1 # Rear 
  }
print(result)
```

```{r}
count1 <- count2 <- 0
coin <- function(n){
    for(i in 1:n){
      if(runif(1) <= 1/2){
        count1 = count1 + 1
      }else{
        count2 = count2 + 1
      }
    }
  cat("앞면 : ",count1,"\n")
  cat("뒷면 : ",count2,"\n")
  cat("----------------------\n")
}

coin(100)
coin(1000)
coin(10000)
coin(100000)
coin(1000000)

```

# 가위, 바위, 보

```{r}
countA <- countB <- countC <- 0

srp2 <- function(n,y){
    for(i in 1:n){
      random <- runif(1)
      if(random <= 1/y){
        countA = countA + 1
      }else if(random < 2/y && random>1/y ){
        countB = countB + 1
      }else{# if(random >=2/y)
        countC = countC +1
      }
    }
  
  cat("scissor :",countA,"\n")
  cat("rock :\t ",countB,"\n")
  cat("paper :\t ",countC,"\n")
  cat("----------------------\n")
}
srp2(1000000,3)

```

### 강사님 답안

```{r}
srp <- function(n){
  scissor <- rock <- paper <- 0
  
    for(i in 1:n){
      x <- trunc(runif(1)*3)+1
      if(x == 1) scissor = scissor +1
      if(x == 2) rock = rock +1
      if(x == 3) paper = paper + 1
    }
  
    cat("scissor :",scissor,"\n")
    cat("rock :\t ",rock,"\n")
    cat("paper :\t ",paper,"\n")
  cat("----------------------\n")
}
```

```{r}
srp(10)
srp(100)
srp(1000)
```

## 주사위 시뮬레이션

강사님 답안

```{r}
dice <- function(n){
  diceFace <- rep(0,6)
  cat("Throw:",n,"\n")
  for(i in 1:n){
    x <- trunc(runif(1)*6)+1
    diceFace[x] = diceFace[x]+1
  }
  for(i in 1:length(diceFace)){
    cat("No",i, " = ", diceFace[i],"\n")
  }
  cat("---------------------------\n")
}
runif(1)
runif(1)*6
```

```{r}
options(scipen = 100) ## e 안보이게 해주는거 
dice(10)
dice(100)
dice(1000)
dice(10000)
dice(100000)
dice(1000000)
```
