# 데이터 시각화2

선 굵기 변경하기

```{r}

x <- c(11,3,5,12,8,21, 22, 13, 7, 18)
plot(
  x,
  type = "b", # 7 번째 
  col = c(rep("black",6),"red",rep("black",3)),
  lwd = c("1","2","3","4","5","6","7","8","9","10")
  )#lwd = "5"
```

# 한 화면에 차트 여러개 그려서 비교하기

```{r}
par(mfrow=c(3,3))
#par(mfrow=c(1,2))

price <- runif(10,1,100)
plot(price, type = 'l')
plot(price, type = 'o')
plot(price, type = 'h')
plot(price, type = 's')
barplot(price)
pie(price)
plot(price, type = 'o', pch = 15, col="blue")
plot(price, type = 'o', pch = 25, col="red", lwd="2")
plot(price, type = 'o', pch = c(rep(20,5),2,4,8,15,17), 
                        col="brown", lwd="1", cex = c(rep(1,8),3,1))
```

### pch 속성으로 그리기

```{r}
par(mfrow=c(2,2))
plot(price, type = 'o', pch = 5)
plot(price, type = 'o', pch = 15, col="blue")
plot(price, type = 'o', pch = 25, col="red", lwd="2")
plot(price, type = 'o', pch = c(rep(20,5),2,4,8,15,17), 
                        col="brown", lwd="1", cex = c(rep(1,8),3,1))
```

### 중첩 자료 시각화

```{r}
x <- c(1,2,3,4,2,4)
y <- rep(2,6)

plot(x,y)



```

```{r}
#table은 빈도수를 나타내주기 때문에 중복된 수를 알 수 있음
table(x,y)

```

### Method #1

```{r}
# 처리하기 편해서 dateframe으로 만듬 
xy.df <- as.data.frame(table(x,y))
xy.df
# Frequancy(?) 는 중복?
```

```{r}
plot(
  x,y,
  pch = 15,
  cex = 2 * xy.df$Freq
  )
```

### Method #2

```{r}
x <- c(1,1,1,2,2,2,2,2,2,3,3,4,5,6)
y <- c(0,2,2,2,2,2,2,2,2,2,2,2,9,1)

zz <- data.frame(x,y)
zz

sunflowerplot(zz)
```

sunflowerplot으로 iris의 Sepal.length와 Sepal.width 의 산포도 그리기

```{r}
sunflowerplot(
  iris$Sepal.Length, 
  iris$Sepal.Width,
  
  
  )
```

# Chart 2개를 겹처서 출력하기

```{r}
x <- 1:10
mycol <- rgb(0,0,1,seq(0,1,0.1))
dotchart(x,col = x)
par(new=T)

barplot(x,col=mycol)
```

# 상자 수염 그래프

: 이상치 확인

```{r}
abc <- c(110,300,150,280,310)

boxplot(
  abc
) # summary 모양을 보는 그래프 라고 생각하면 댐 
```

```{r}
boxplot(
  abc,
  col = "yellow",
  horizontal = T
) 
```

```{r}
def<- c(1,1,1,1,1,2,5)
summary(def)
```

```{r}
boxplot(def)   #  5에 있는 점 하나가 이상치로 확인이 되는것
```

### 자동차의 제동거리

```{r}
head(cars)
```

```{r}
str(cars)
```

```{r}
plot(cars$speed, cars$dist)
```

```{r}
hist(cars$dist)
```

```{r}
boxplot(cars$dist)
```

이상치와 결측치가 총 데이터 량의 40%가 넘어가면 사용 할 수 없는 데이터

# 차트 디자인

```{r}
par(family = "AppleGothic")
x <- c( 1, 3, 6, 8,9)
y <- c(12,56,78,32,9)

plot(x,y)

# (3,3) 과 (4,4)를 연결하는 선분 그리기

segments(6,78, 8,32, col = " blue ")

# 화살표 그리기
arrows(3,56, 1,12)
arrows(1,1, 3,45, col="red")

#글자쓰기
text(4,40, "This is a Sample", srt=50) # srt 회전율 

#테두리 활용하기
mtext("Character",side= 4, adj=0.5)
mtext("mtext 1번 위치",side= 1, adj=1)
mtext("mtext 2번 위치",side= 2, col="red",adj=0)

#테두리 그리기
box(lty=5, col="red") # 테두리가 바뀐게 아니라 레이어 하나 씌워져있다고 생각하면 됨

# 사각형 그리기
rect(4,20, 6,30, density=10, col="green")

# X축 추가, Y축의 40 위치에 0~10 까지 표시하고 색은 빨간색
axis(1, pos=40, at=0:10, col="red")

# Y축 추가, X축의 6위치에 20~60까지 표시하고 색은 파란색
axis(2, pos=6, at=20:60, col="blue")

```

# 
