# 투표수가 높은 시군구의 후보별 득표수의 막대그래프에 시군구별 투표수 표시하기

1.  투표수가 높은 시군구 정렬 (5개)
2.  aggregate 로 후보별 득표수 정렬
3.  막대그래프

```{r}
#str
library(stringr)
# arrange
library(dplyr)
```

### 데이터 불러오기

```{r}
election <- read.csv("./Data/election_2022.csv")

head(election)
```

### 칼럼 정렬

```{r}
# 선거인수 제거 
election <- election[,-3]
election

# 중복데이터 있음
length(election$시군구) # = 248
length(unique(election$시군구)) # = 226

# na 없음 
sum(is.na(election)) 
```

### 투표수가 높은 5시군구

```{r}
election

elec_top5 <- arrange(election, desc(투표수)) [1:5,c(1:2,4:6)]
elec_top5

# 차트에 쓸 매트릭스 형식으로 변환 
elec_top5_matrix <- as.matrix(t(elec_top5[,3:5]))
elec_top5_matrix
```

### 총 투표수 계산

```{r}
#각 지역별 총 투표수 계산하기
sum(elec_top5[,3])

apply(elec_top5[,3:5],1,sum) # = integer


```

```{r}
# 광역시도와 시군구 합치기 
t(as.matrix(elec_top5[,1:2]))
paste(as.matrix(elec_top5[1:5,1]),as.matrix(elec_top5[1:5,2]))


```

# Chart 막대기 위에 총 투표율 작성 (완 )

```{r}
par(family="AppleGothic")
options(scipen=999)

barplot(
 elec_top5_matrix,
  col=c("skyblue","red","yellow"),
  ylim=c(0,600000),
  legend.text = T,
  names=c(paste(as.matrix(elec_top5[1:5,1]),as.matrix(elec_top5[1:5,2]))),
  cex.axis=0.5,
  main = "투표수가 높은 시군구의 후보별 득표수",
  space = 0.6,
  cex.names = 0.7
  
  )
line<-1.1
for (i in 1:ncol(elec_top5_matrix)) {
  data=sum(elec_top5_matrix[,i])
  text(line,data+19000,data,cex = 0.8)
  line=line+1.6
}
```

# 각 후보별 투표율

```{r}
elec_top5
elec_top5[,3:5]

```

```{r}
# 계산식 확인 
for (i in nrow(elec_top5[,3:5])){
}
apply(elec_top5[i,3:5],1,sum)
```

# chart 각 후보별 투표율 (완)

```{r}
par(family="AppleGothic")
options(scipen=999)
barplot(
  as.matrix(t(elec_top5[,3:5])),
  col=c("skyblue","red","yellow"),
  ylim=c(0,600000),
  legend.text = T,
  names=c(paste(as.matrix(elec_top5[1:5,1]),as.matrix(elec_top5[1:5,2]))),
  cex.axis=0.5,
  space = 0.6,
  cex.names = 0.7
  
  )


line<-1.1


for ( i in 1:5 ){
  text(
    line,elec_top5[i,3]/2,
      paste(round((elec_top5[i,3] / apply(elec_top5[i,3:5],1,sum)) * 100,2),"%"),
    cex = 0.7)
  
  text(
    line,(((elec_top5[i,3]*2)+ elec_top5[i,4])/2),
    paste(round((elec_top5[i,4] / apply(elec_top5[i,3:5],1,sum)) * 100,2),"%"),
    cex = 0.7)
  
  text(
    line,( ((elec_top5[i,3]+elec_top5[i,4])*2) + elec_top5[i,5])/2,
  paste(round((elec_top5[i,5] / apply(elec_top5[i,3:5],1,sum)) * 100,2),"%"),
    cex = 0.7)
  
  line=line+1.6
}

```

## qplot() 을 이용한 산점도

```{r}
#install.packages("ggplot2")
library(ggplot2)
```

```{r}
qplot(Sepal.Length, Petal.Length, data = iris)
```

# 수학 함수의 시각화

y = x\^2

```{r}
f<- function(x){
  y = x ^ 2 
  return(y)
}
#= f(x) = x^2
```

```{r}
x<- 1:3
f(x)
```

```{r}
x<- seq(-5, 5 , 0.1)
plot(
  x,f(x),
  type = 'l'
     )
```

### y=x\^2 +2x +3 를 시각화 해보세요

```{r}
ff<- function(x){
  y=x^2+2*x +3
  return(y)
}
```

```{r}
x<- seq(-5, 5 , 0.1)
plot(
  x,ff(x),
  type = 'l'
     )
```
