# 인공신경망을 이용한 평균 예측율 구하기

```{r}
library(nnet)
library(randomForest)
library(caret)
library(e1071)
```

## 인공신경망 

```{r}
nnetFun <- function(n){
  for (i in 1:n){
    if(i == 1){
      resultVec = c()
    }#if end
    samp <- createDataPartition(iris$Species, p=0.7, list=F)
    data.train <- iris[samp,]
    data.test <- iris[-samp,]
    x <- subset ( data.test, select = -Species)
    y <- data.test$Species
    model.nnet <- nnet(Species ~ ., data = data.train, size = 3)
    pred.nnet <- predict(model.nnet , x, type = 'class')
    resultVec = append(resultVec, mean(pred.nnet == y))
  }#for end
  cat("---------------------------------------------\n")
  cat("예측율 \n")
  cat(resultVec,"\n")
  cat("---------------------------------------------\n")
  cat("평균예측율 : ",mean(resultVec),"\n")
  cat("---------------------------------------------\n")
}
```

```{r}
nnetFun(5)
```

## randomForest의 평균 예측율 함수 추가하기

```{r}
# randomForest 의 평균 예측율 함수 추가하기

rfFun <- function(n){
 for (i in 1:n){
    if(i == 1){
      resultVec = c()
    }#if end
    samp <- createDataPartition(iris$Species, p=0.7, list=F)
    data.train <- iris[samp,]
    data.test <- iris[-samp,]
    x <- subset ( data.test, select = -Species)
    y <- data.test$Species
    rf <- randomForest(Species ~ ., data = data.train, ntree = 100) 
    pred <- predict(rf, x)
    resultVec = append(resultVec, mean(pred == y))
  }#for end
  cat("---------------------------------------------\n")
  cat("예측율 \n")
  cat(resultVec,"\n")
  cat("---------------------------------------------\n")
  cat("평균예측율 : ",mean(resultVec),"\n")
  cat("---------------------------------------------\n")
}


```

```{r}
rfFun(100)
```

## SVM의 평균 예측율 함수 구하기

```{r}
# SVM 의 평균 예측율 함수 추가하기

svmFun <- function(n){
 for (i in 1:n){
    if(i == 1){
      resultVec = c()
    }#if end
    samp <- createDataPartition(iris$Species, p=0.7, list=F)
    data.train <- iris[samp,]
    data.test <- iris[-samp,]
    x <- subset ( data.test, select = -Species)
    y <- data.test$Species
    model <- svm(Species ~., data = data.train)
    pred <- predict(model,x)
    resultVec = append(resultVec, mean(pred == y))
  }#for end
  cat("---------------------------------------------\n")
  cat("예측율 \n")
  cat(resultVec,"\n")
  cat("---------------------------------------------\n")
  cat("평균예측율 : ",mean(resultVec),"\n")
  cat("---------------------------------------------\n")
}



```

```{r}
svmFun(100)
```

```{r}

```
