# chart

```{r}
#str
library(stringr)
# arrange
library(dplyr)
```

### 데이터 불러오기

```{r}
head(read.csv("./행정안전부_주민등록_인구_및_세대현황.csv"))[,-1]


```

### 02. 주민등록 인구 및 세대현황 Fdata1421

```{r}
Fdata1421
```

### 년도별 각 지자체 인구수 \_1

```{r}
# 나이를 없애고 년도별로 인구수 합침

dfGachi <-
aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata1421, sum)

dfGachi
```

### 년도별 국내 인구수

```{r}
# 지자체의 인구를 년도별로 모두 합침 
dfGachi

apply(dfGachi, 1, sum)

```

```{r}
par(family="AppleGothic")
options(scipen=999)
plot(
  apply(dfGachi, 1, sum)/1000,
  main = "2014 ~ 2021 년 대한민국 인구수",
  ylab = "인구수 ( 단위 : 천명)",
  xlab = "년도",
  ylim=c(50000,53000),
  #names=c("2014","2015","2016","2017","2018","2019","2020","2021"),
 axes = F, # frame 없애기 
  #ann = F,  # 왼쪽 abc랑 밑에 index 없애기 
  #type='l'
 type='both'
  )

axis(  # 새로 만들기
  1, #x축에 대해서 만들거야 
  at = 1:8,
  #lab = c("2014","2015","2016","2017","2018","2019","2020","2021"),
  lab = c(2014:2021),
  
  cex.axis=0.9
)
axis(
  2, #y축 만들기 
)
```

```{r}
par(family="AppleGothic")
barplot(
 apply(dfGachi, 1, sum)/1000,
   main = "2014 ~ 2021 년 대한민국 인구수",
  ylab = "인구수 ( 단위 : 천명)",
  xlab = "년도",
  ylim=c(0000,60000),
  names.arg = c(2014:2021),
)
# 
# axis(  # 새로 만들기
#   1, #x축에 대해서 만들거야 
#   at = 1:8,
#   #lab = c("2014","2015","2016","2017","2018","2019","2020","2021"),
#   lab = c(2014:2021),
#   
#   cex.axis=0.9
# )
# axis(
#   2, #y축 만들기 
# )
```

### 대한민국의 인구수는 14년부터 21년가지 유의미한 변화는 없다

### 14년도 인구층을 3분할

```{r}
Fdata14 <- Fdata1421[1:11,]
Fdata14

# 미성년자 
Fdata14o2050un20 <- subset(Fdata14, 나이 == c('0-9','10-19'))
Fdata14o2050un20 <-  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata14o2050un20, sum)

# 20 ..< 60
Fdata14o2050 <- rbind(
  subset(Fdata14, 나이 == c('20-29','30-39')),
      subset(Fdata14, 나이 == c('40-49','50-59'))
      )
Fdata14o2050 <- 
  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata14o2050, sum)

# 60대 이상 
Fdata14o60 <- rbind(
  subset(Fdata14, 나이==c('60-69','70-79')),
  subset(Fdata14, Fdata14$나이==c('80-89','90-99')),
  subset(Fdata14, 나이==c('100-'))
)

Fdata14o60 <- 
aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata14o60, sum)

# 14년 20 미만, 20~50대 , 60대이상으로 합쳐서 지역별로 맞춤 
Fdata14u2050o60 <- rbind(Fdata14o2050un20, Fdata14o2050, Fdata14o60)
Fdata14u2050o60

# 14년 20 미만, 20~50대 , 60대이상으로 3분할 총 인구수로만 사용
Fdata14_2050 <- as.matrix(apply(Fdata14u2050o60,1,sum))
Fdata14_2050
```

### 15년도 인구층을 3분할

```{r}

Fdata15 <- Fdata1421[12:22,]
Fdata15
Fdata1421
# 미성년자 
Fdata15o2050un20 <- subset(Fdata15, 나이 == c('0-9','10-19'))
Fdata15o2050un20 <-  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata15o2050un20, sum)

# 20 ..< 60
Fdata15o2050 <- rbind(
  subset(Fdata15, 나이 == c('20-29','30-39')),
      subset(Fdata15, 나이 == c('40-49','50-59'))
      )
Fdata15o2050 <- 
  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata15o2050, sum)

# 60대 이상 
Fdata15o60 <- rbind(
  subset(Fdata15, 나이==c('60-69','70-79')),
  subset(Fdata15, 나이==c('80-89','90-99')),
  subset(Fdata15, 나이==c('100-'))
)

Fdata15o60 <- 
aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata15o60, sum)

# 15년 20 미만, 20~50대 , 60대이상으로 합쳐서 맞춤 
Fdata15u2050o60 <- rbind(Fdata15o2050un20, Fdata15o2050, Fdata15o60)
Fdata15u2050o60


# 15년 20 미만, 20~50대 , 60대이상으로 3분할 총 인구수로만 사용
Fdata15_2050 <- as.matrix(apply(Fdata15u2050o60,1,sum))
Fdata15_2050
```

### 16년도 인구층을 3분할

```{r}
Fdata16 <- Fdata1421[23:33,]
Fdata16

# 미성년자 
Fdata16o2050un20 <- subset(Fdata16, 나이 == c('0-9','10-19'))
Fdata16o2050un20 <-  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata15o2050un20, sum)

# 20 ..< 60
Fdata16o2050 <- rbind(
  subset(Fdata16, 나이 == c('20-29','30-39')),
      subset(Fdata16, 나이 == c('40-49','50-59'))
      )

Fdata16o2050 <- 
  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata16o2050, sum)

# 60대 이상 
Fdata16o60 <- rbind(
  subset(Fdata16, 나이==c('60-69','70-79')),
  subset(Fdata16, 나이==c('80-89','90-99')),
  subset(Fdata16, 나이==c('100-'))
)

Fdata16o60 <- 
aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata16o60, sum)

# 15년 20 미만, 20~50대 , 60대이상으로 합쳐서 맞춤 
Fdata16u2050o60 <- rbind(Fdata16o2050un20, Fdata16o2050, Fdata16o60)
Fdata16u2050o60


# 15년 20 미만, 20~50대 , 60대이상으로 3분할 총 인구수로만 사용
Fdata16_2050 <- as.matrix(apply(Fdata16u2050o60,1,sum))
Fdata16_2050
```

### 17년도 인구층을 3분할

```{r}
Fdata1421[34:44,]
Fdata17 <- Fdata1421[34:44,]


# 미성년자 
Fdata17o2050un20 <- subset(Fdata17, 나이 == c('0-9','10-19'))
Fdata17o2050un20 <-  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata17o2050un20, sum)

# 20 ..< 60
Fdata17o2050 <- rbind(
  subset(Fdata17, 나이 == c('20-29','30-39')),
      subset(Fdata17, 나이 == c('40-49','50-59'))
      )

Fdata17o2050 <- 
  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata17o2050, sum)

# 60대 이상 
Fdata17o60 <- rbind(
  subset(Fdata17, 나이==c('60-69','70-79')),
  subset(Fdata17, 나이==c('80-89','90-99')),
  subset(Fdata17, 나이==c('100-'))
)

Fdata17o60 <- 
aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata17o60, sum)

##########

# 15년 20 미만, 20~50대 , 60대이상으로 합쳐서 맞춤 
Fdata17u2050o60 <- rbind(Fdata17o2050un20, Fdata17o2050, Fdata17o60)
Fdata17u2050o60


# 15년 20 미만, 20~50대 , 60대이상으로 3분할 총 인구수로만 사용
Fdata17_2050 <- as.matrix(apply(Fdata17u2050o60,1,sum))
Fdata17_2050
```

### 18년도 인구층을 3분할

```{r}
Fdata1421[45:55,]
Fdata18 <- Fdata1421[45:55,]


# 미성년자 
Fdata18o2050un20 <- subset(Fdata18, 나이 == c('0-9','10-19'))
Fdata18o2050un20 <-  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata18o2050un20, sum)

# 20 ..< 60
Fdata18o2050 <- rbind(
  subset(Fdata18, 나이 == c('20-29','30-39')),
      subset(Fdata18, 나이 == c('40-49','50-59'))
      )

Fdata18o2050 <- 
  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata18o2050, sum)

# 60대 이상 
Fdata18o60 <- rbind(
  subset(Fdata18, 나이==c('60-69','70-79')),
  subset(Fdata18, 나이==c('80-89','90-99')),
  subset(Fdata18, 나이==c('100-'))
)

Fdata18o60 <- 
aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata18o60, sum)

##########

# 15년 20 미만, 20~50대 , 60대이상으로 합쳐서 맞춤 
Fdata18u2050o60 <- rbind(Fdata18o2050un20, Fdata18o2050, Fdata18o60)
Fdata18u2050o60


# 15년 20 미만, 20~50대 , 60대이상으로 3분할 총 인구수로만 사용
Fdata18_2050 <- as.matrix(apply(Fdata18u2050o60,1,sum))

```

### 19년도 인구층을 3분할

```{r}
Fdata1421[56:66,]
Fdata19 <- Fdata1421[56:66,]


# 미성년자 
Fdata19o2050un20 <- subset(Fdata19, 나이 == c('0-9','10-19'))
Fdata19o2050un20 <-  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata19o2050un20, sum)

# 20 ..< 60
Fdata19o2050 <- rbind(
  subset(Fdata19, 나이 == c('20-29','30-39')),
      subset(Fdata19, 나이 == c('40-49','50-59'))
      )

Fdata19o2050 <- 
  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata19o2050, sum)

# 60대 이상 
Fdata19o60 <- rbind(
  subset(Fdata19, 나이==c('60-69','70-79')),
  subset(Fdata19, 나이==c('80-89','90-99')),
  subset(Fdata19, 나이==c('100-'))
)

Fdata19o60 <- 
aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata19o60, sum)

##########

# 15년 20 미만, 20~50대 , 60대이상으로 합쳐서 맞춤 
Fdata19u2050o60 <- rbind(Fdata19o2050un20, Fdata19o2050, Fdata19o60)
Fdata19u2050o60


# 15년 20 미만, 20~50대 , 60대이상으로 3분할 총 인구수로만 사용
Fdata19_2050 <- as.matrix(apply(Fdata19u2050o60,1,sum))
Fdata19_2050
```

### 20년도 인구층을 3분할

```{r}
Fdata1421[67:77,]
Fdata20 <- Fdata1421[67:77,]
Fdata20

# 미성년자 
Fdata20o2050un20 <- subset(Fdata20, 나이 == c('0-9','10-19'))
Fdata20o2050un20 <-  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata20o2050un20, sum)

# 20 ..< 60
Fdata20o2050 <- rbind(
  subset(Fdata20, 나이 == c('20-29','30-39')),
      subset(Fdata20, 나이 == c('40-49','50-59'))
      )

Fdata20o2050 <- 
  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata20o2050, sum)

# 60대 이상 
Fdata20o60 <- rbind(
  subset(Fdata20, 나이==c('60-69','70-79')),
  subset(Fdata20, 나이==c('80-89','90-99')),
  subset(Fdata20, 나이==c('100-'))
)

Fdata20o60 <- 
aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata20o60, sum)

##########

# 15년 20 미만, 20~50대 , 60대이상으로 합쳐서 맞춤 
Fdata20u2050o60 <- rbind(Fdata20o2050un20, Fdata20o2050, Fdata20o60)
Fdata20u2050o60


# 15년 20 미만, 20~50대 , 60대이상으로 3분할 총 인구수로만 사용
Fdata20_2050 <- as.matrix(apply(Fdata20u2050o60,1,sum))
Fdata20_2050
```

### 21년도 인구층을 3분할

```{r}
Fdata1421[78:88,]
Fdata21 <- Fdata1421[78:88,]
Fdata21

# 미성년자 
Fdata21o2050un20 <- subset(Fdata21, 나이 == c('0-9','10-19'))
Fdata21o2050un20 <-  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata21o2050un20, sum)

# 20 ..< 60
Fdata21o2050 <- rbind(
  subset(Fdata21, 나이 == c('20-29','30-39')),
      subset(Fdata21, 나이 == c('40-49','50-59'))
      )

Fdata21o2050 <- 
  aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata21o2050, sum)

# 60대 이상 
Fdata21o60 <- rbind(
  subset(Fdata21, 나이==c('60-69','70-79')),
  subset(Fdata21, 나이==c('80-89','90-99')),
  subset(Fdata21, 나이==c('100-'))
)

Fdata21o60 <- 
aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , Fdata21o60, sum)

##########

# 15년 20 미만, 20~50대 , 60대이상으로 합쳐서 맞춤 
Fdata21u2050o60 <- rbind(Fdata21o2050un20, Fdata21o2050, Fdata21o60)
Fdata21u2050o60


# 15년 20 미만, 20~50대 , 60대이상으로 3분할 총 인구수로만 사용
Fdata21_2050 <- as.matrix(apply(Fdata21u2050o60,1,sum))

```

## 3분할 합치기

```{r}

# 14~21 년 따로 만든 데이터 합치기 
y1421hap3bun <- as.matrix(data.frame(cbind(Fdata14_2050,
Fdata15_2050,Fdata16_2050,Fdata17_2050,Fdata18_2050,Fdata19_2050,Fdata20_2050,Fdata21_2050)))



# y1421hap3bun col, row names 넣기
colnames(y1421hap3bun) <- 2014:2021
rownames(y1421hap3bun) <- c('20 미만 ','20 ~ 56 살','60살 이상')


y1421hap3bun

```

## Chart

```{r}

# 차트 
par(family="AppleGothic")#, oma=c(3,3,3,3) )
options(scipen=999)


barplot(
 y1421hap3bun,
 main = "2014 ~ 2021 년 대한민국 연령층 인구분포",
 ylab = "인구수 ( 단위 : 명)",
 xlab = "년도",
 ylim=c(0,60000000),
 names.arg = c(2014:2021),
 col = c("orange",'green','red'),
  space = 0.9, 
  width = 0.7
)
legend(
  9.4,61500000,
  legend=c("~20","20~60","60~"),
  fill=c("orange",'green','red'),
  border="white",
  box.lty=0,
  cex=0.58,
  )


```

## 결론

상기 데이터로 대한민국은 총 인구수에 큰 변화없이 고령화 가 진행되고 있음을 확인할 수 있다
