# 지역별 고령자 인구분포

### 2021년 기준 지역별 연령분포

```{r}
#str
library(stringr)
# arrange
library(dplyr)
# 3D chart
library(plotrix)
```

Data 불러오기

```{r}
y21_age <- read.csv("./행정안전부_주민등록_인구_및_세대현황.csv" , header = T)[,-1]

y21_age
```

### 60대 이상 인구 증감차트

```{r}

par(family="AppleGothic")#, oma=c(3,3,3,3) )
options(scipen=999)


barplot(
   apply(y1421_age60100, 1, sum),
 main = "2014 ~ 2021 년 60대 이상 인구 증감표",
 ylab = "인구수 ( 단위 : 명)",
 xlab = "년도",
 ylim=c(0,20000000),
 names.arg = c(2014:2021),
 #col = c("orange",'green','red'),
  space = 0.9, 
  width = 0.7
)

```

### 60이상 나이층 지역별 인구 합치기

```{r}
 # for 문으로 만들고 싶은데 시간부족으로 빠르게 직접 만들거임 


y21_age[7:11,] # 14년도 60대 이상 
y21_age[18:22,] # 15년도 
y21_age[29:33,] # 16년도  
y21_age[40:44,] # 17년도 
y21_age[51:55,] # 18년도 
y21_age[62:66,] # 19년도 
y21_age[73:77,] # 20년도 
y21_age[84:88,] # 21년도


y14_age100 <- aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , y21_age[7:11,], sum)

y15_age100 <- aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , y21_age[18:22,], sum)

y16_age100 <- aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , y21_age[29:33,], sum)

y17_age100 <- aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , y21_age[40:44,], sum)

y18_age100 <- aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , y21_age[51:55,], sum)

y19_age100 <- aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , y21_age[62:66,] , sum)

y20_age100 <- aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , y21_age[73:77,], sum)


y21_age100 <- aggregate(cbind(서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별시) ~ 년도 , y21_age[84:88,], sum)

y14_age100
y15_age100
y16_age100
y17_age100
y18_age100
y19_age100
y20_age100
y21_age100


```

### row 합치기

```{r}
# 14~21 년 60대 이상 지역별 인구수 합치기 
y1421_age60100 <- rbind(y14_age100,y15_age100,y16_age100,y17_age100,y18_age100,y19_age100,y20_age100,y21_age100)

y1421_age60100
y1421_age60100t <- t(y1421_age60100)
as.data.frame(y1421_age60100t)

 
```

```{r}
y1421_age60100
apply(y1421_age60100, 1, sum)

```

### Chart 연도별 지역별 60대 이상 인구 증감율

```{r}



par(family="AppleGothic")
options(scipen=999)
 plot(
 sort(t(y14_age100)[-1,], decreasing = T),
   type = 'o', 
   col = 1, 
   ylim = c(0,3500000),
   main = "2014 ~ 2021 년 자치구별 60대 이상 인구분포",
  ylab = "인구수 ( 단위 : 명)",
  xlab = "자치구명",
  axes = F, # frame 없애기 
  #ann = F,  # 왼쪽 abc랑 밑에 index 없애기 
 
   )
 
 
lines(
 sort(t(y15_age100)[-1,], decreasing = T),
 type = 'o', 
 col = 2)
  
lines(
 sort(t(y16_age100)[-1,], decreasing = T),
 type = 'o', 
 col = 3)
  
lines(
 sort(t(y17_age100)[-1,], decreasing = T),
 type = 'o', 
 col = 4)
  
lines(
 sort(t(y18_age100)[-1,], decreasing = T),
 type = 'o', 
 col = 5)
  
lines(
 sort(t(y19_age100)[-1,], decreasing = T),
 type = 'o', 
 col =6 )
  
lines(
 sort(t(y20_age100)[-1,], decreasing = T),
 type = 'o', 
 col = 7)
  
lines(
 sort(t(y21_age100)[-1,], decreasing = T),
 type = 'o', 
 col = 8)
  
legend(
  #15,2400000,
  "topright",
 #c(seq(2014,2021,1)),
 #c('2014','2015','2016','2017','2018','2019','2020','2021'),
 c('2021','2020','2019','2018','2017','2016','2015','2014'),
  cex = 0.8, 
  pch = 1, 
  col = 8:1, 
  lty = 1,
)

axis(  # 새로 만들기
  1, #x축에 대해서 만들거야 
  at = 1:17,
  lab = c('경기도','서울특별시','부산광역시','경상북도','경상남도','전라남도','대구광역시','충청남도','인천광역시','전라북도','강원도','충청북도','대전광역시','광주광역시','울산광역시','제주특별시','세종특별시'),
  cex.axis=0.32
)

axis(
  2, #y축 만들기 
  #ylim = c(0,400)
)
              
```
