```{r}
library(caret)
library(randomForest)
library(dplyr)
library(stringr)
library(party)
# 인공신경망
library(nnet)
# SVM
library(e1071)
```

```{r}
GAM <- read.csv('./Data/changeEducNewGAM.csv')[,-1]
PlusGAM <- read.csv('./Data/dementiaAgeAll.csv')
PlusGAM<-rename(PlusGAM, EDUC=Educ)
PlusGAM$CDR <- str_replace(PlusGAM$CDR, '2', '1')
```

```{r}
Data <- rbind(GAM, PlusGAM)
```

```{r}
Data
```

======================================================

### 사용할 컬럼 전부 다

CDR factor로 바꾸기

```{r}
Data$CDR <- as.factor(Data$CDR)
```

```{r}
str(Data)
```

### CDR 별로 나누기

```{r}
CDR1 <- subset(Data, CDR == '1')
nrow(CDR1) # = 64
CDR5 <- subset(Data, CDR == '0.5')
nrow(CDR5) # = 167
CDR0 <- subset(Data, CDR == '0')
nrow(CDR0) # = 338
nrow(CDR1)+nrow(CDR5)+nrow(CDR0) # = 569
```

==================================================================

### sample Data

```{r}
sample <- sample(1:64,64)

test.CDR1 <- CDR1[sample,]
test.CDR5 <- CDR5[sample,]
test.CDR0 <- CDR0[sample,]

#data.CDR1 <- CDR1[-sample,]  # 38 다 사용해서 CDR1은 그대로 사용 // 추가되서 살림  
#nrow(data.CDR1)
data.CDR5 <- CDR5[-sample,] 
#nrow(data.CDR5)
data.CDR0 <- CDR0[-sample,] 
#nrow(data.CDR0)
#data.CDR5


testCDR <- rbind(test.CDR1,test.CDR0,test.CDR5)
#dataCDR <- rbind(data.CDR1,data.CDR5,data.CDR0)  # 38 다 사용해서 CDR1은 그대로 사용 
          # 추가되서 살림 
dataCDR <- rbind(test.CDR1,data.CDR5,data.CDR0)
#dataCDR
nrow(dataCDR) #
nrow(testCDR) #

# rbind 한거 순서 한번 섞기
sample <- sample(1:192,192)
testCDR <- testCDR[sample,]


sample <- sample(1:441,441)
dataCDR <- dataCDR[sample,]

```

=================================================================

### AI

# 인공신경망

```{r}
x <- subset(testCDR , select = -CDR)
y <- testCDR$CDR
```

```{r}
model.nnet <- nnet(CDR ~ ., data = dataCDR, size = 3)
pred <- predict(model.nnet, x, type = "class")
pred
```

```{r}
pred == y
mean(pred == y)*100
table(pred,y)
```

# RandomForest

```{r}
x <- subset(testCDR, select = -CDR)
y <- testCDR$CDR
```

```{r}
rf <- randomForest(CDR ~ ., data = dataCDR, ntree = 100) 
rf
```

```{r}
pred <- predict(rf, x)
mean(pred == y)
table(pred,y)
```

# SVM

```{r}
x <- subset(testCDR, select = -CDR)
y <- testCDR$CDR
model <- svm(CDR ~., data = dataCDR)
```

```{r}
pred <- predict(model,x)
mean(pred == y)
table(pred,y)
```

# 의사결정나무

```{r}
x <- subset(testCDR, select = -CDR)
y <- testCDR$CDR
#학습시키기
dementia_tree <- ctree(CDR ~ ., data = dataCDR)
pred <- predict(dementia_tree, x)
```

```{r}
mean(pred == y)
table(pred, y)
```
