```{r}
GAM <- read.csv('./Data/changeEducNewGAM.csv')[,-1]
PlusGAM <- read.csv('./Data/PlushAddAllData.csv')[,-1]
```

```{r}
library(caret)
library(randomForest)
library(dplyr)
library(stringr)
library(party)
# 인공신경망
library(nnet)
# SVM
library(e1071)
```

======================================================

### 사용할 컬럼 전부 다

```{r}
GAM
PlusGAM

nrow(GAM) # = 353
nrow(PlusGAM) # = 180

nrow(GAM)+nrow(PlusGAM) # = 533

Data <- rbind(GAM,PlusGAM)
str(Data)
nrow(subset(Data, CDR == 1))
```

CDR factor로 바꾸기

```{r}
Data$CDR <- as.factor(Data$CDR)
```

### CDR 별로 나누기

```{r}
Data1 <- subset(Data, CDR == '1')
Data5 <- subset(Data, CDR == '0.5')
Data0 <- subset(Data, CDR == '0')
```

=================================================================

### sample Data

```{r}
sample <- sample(1:64,64)

test.CDR1 <- Data1[sample,]
test.CDR5 <- Data5[sample,]
test.CDR0 <- Data0[sample,]

#data.CDR1 <- Data1[-sample,]  # 64로우 다 사용해서 Data1은 그대로 사용  
data.CDR5 <- Data5[-sample,] 
data.CDR0 <- Data0[-sample,] 


testCDR <- rbind(test.CDR1,test.CDR0,test.CDR5)
dataCDR <- rbind(test.CDR1,data.CDR5,data.CDR0)


# rbind 한거 순서 한번 섞기
sample <- sample(1:192,192)
testCDR <- testCDR[sample,]


sample <- sample(1:405,405)
dataCDR <- dataCDR[sample,]

```

=================================================================

### AI

# 인공신경망

```{r}
x <- subset(testCDR , select = -CDR)
y <- testCDR$CDR
```

```{r}
model.nnet <- nnet(CDR ~ ., data = dataCDR, size = 3)
pred <- predict(model.nnet, x, type = "class")
pred
```

```{r}
pred == y
mean(pred == y)*100
table(pred,y)
```

# RandomForest

```{r}
x <- subset(testCDR, select = -CDR)
y <- testCDR$CDR
rf <- randomForest(CDR ~ ., data = dataCDR, ntree = 100) 
rf
```

```{r}
pred <- predict(rf, x)
mean(pred == y)
table(pred,y)
```

```{r}

```

```{r}
# SAVE
rf <- randomForest(CDR ~ ., data = Data, ntree = 100) 
saveRDS(rf,'./AI/randomForest_dementia_final_82.rds')
```

# SVM

```{r}
x <- subset(testCDR, select = -CDR)
y <- testCDR$CDR
model <- svm(CDR ~., data = dataCDR)
```

```{r}
pred <- predict(model,x)
mean(pred == y)
table(pred,y)
```

# 의사결정나무

```{r}
x <- subset(testCDR, select = -CDR)
y <- testCDR$CDR
#학습시키기
dementia_tree <- ctree(CDR ~ ., data = dataCDR)
pred <- predict(dementia_tree, x)
```

```{r}
mean(pred == y)
table(pred, y)
```
